# app.yaml - Configuración para Google Cloud App Engine

runtime: python311

env: standard
instance_class: F2

entrypoint: streamlit run frontend/app.py --server.port=8080 --server.address=0.0.0.0

env_variables:
  PORT: "8080"

runtime_config:
  python_version: 3.11

handlers:
  - url: /.*
    secure: always
    script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 10
  min_pending_latency: 1s
  max_pending_latency: 5s

vpc_access_connector:
  name: "projects/PROJECT_ID/locations/us-central1/connectors/pixely-connector"
