steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pixely-partners-frontend'
      - '-f'
      - 'Dockerfile.frontend'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/pixely-partners-frontend'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=.
      - --image=gcr.io/$PROJECT_ID/pixely-partners-frontend
      - --location=us-central1
      - --filename=k8s/

images:
  - 'gcr.io/$PROJECT_ID/pixely-partners-frontend'
